[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { version = "0.4.25", features = ["std"] }
pollster = "0.4.0"
wgpu = "24.0.1"
winit = "0.30.8"
glam = { version = "0.29.2", features = ["bytemuck"] }
bytemuck = "1.21.0"
env_logger = "0.11.6"
